# Generated by Django 4.0.3 on 2022-12-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_feedback_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Contact',
        ),
    ]
