# Generated by Django 4.0.3 on 2022-12-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_feedback_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='up_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='up_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
